# Generated by Django 5.2.8 on 2025-11-22 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('size', models.FloatField(help_text='Size in hectares', validators=[django.core.validators.MinValueValidator(0)])),
                ('crop_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farm Profile',
                'verbose_name_plural': 'Farm Profiles',
                'db_table': 'farm_profile',
                'ordering': ['owner'],
                'indexes': [models.Index(fields=['owner'], name='farm_profil_owner_15de65_idx'), models.Index(fields=['location'], name='farm_profil_locatio_e643f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variety', models.CharField(max_length=100)),
                ('plot_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='crop_app.farmprofile')),
            ],
            options={
                'verbose_name': 'Field Plot',
                'verbose_name_plural': 'Field Plots',
                'db_table': 'field_plot',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anomaly_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('model_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='crop_app.fieldplot')),
            ],
            options={
                'verbose_name': 'Anomaly Event',
                'verbose_name_plural': 'Anomaly Events',
                'db_table': 'anomaly_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_type', models.CharField(choices=[('moisture', 'Moisture'), ('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=20)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('source', models.CharField(default='simulator', max_length=100)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='crop_app.fieldplot')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'db_table': 'sensor_reading',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommended_action', models.CharField(max_length=200)),
                ('explanation_text', models.TextField()),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('anomaly_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='crop_app.anomalyevent')),
            ],
            options={
                'verbose_name': 'Agent Recommendation',
                'verbose_name_plural': 'Agent Recommendations',
                'db_table': 'agent_recommendation',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['confidence'], name='agent_recom_confide_787830_idx'), models.Index(fields=['anomaly_event'], name='agent_recom_anomaly_4d4499_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fieldplot',
            index=models.Index(fields=['crop_variety'], name='field_plot_crop_va_a816db_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldplot',
            index=models.Index(fields=['farm'], name='field_plot_farm_id_6e3349_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['severity'], name='anomaly_eve_severit_710e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['anomaly_type'], name='anomaly_eve_anomaly_7a8ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['plot', 'timestamp'], name='anomaly_eve_plot_id_7719fa_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor_type'], name='sensor_read_sensor__6a4090_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['timestamp'], name='sensor_read_timesta_7dba3a_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['plot', 'timestamp'], name='sensor_read_plot_id_d0feb0_idx'),
        ),
    ]
