# Generated by Django 5.2.8 on 2025-11-25 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='farmprofile',
            new_name='farm_profil_owner_i_781bc0_idx',
            old_name='farm_profil_owner_15de65_idx',
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
